title:               jongdory's blog
url:                 https://jongdory.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false


sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Jonghun Kim
  url:               jongdory.github.io
  email:             jongdory@elayda.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist